---
config:
  platform: linux
  image_resource:
    type: docker-image
    source: {repository: golang}
  run:
    path: sh
    args:
    - -exc
    - |
      ./artifact/super_0.0.1_linux_amd64&
      ./super-app/scripts/test_integeration.sh  http://127.0.0.1:8080
      kill -9 `pgrep super_`
  inputs:
    - name: super-app
    - name: artifact