---
resources:
  - name: super-app
    type: git
    source:
      uri: https://github.com/hellofresh/concourse-tutorial.git
      branch: ci

jobs:
  - name: Testing
    plan:
    - get: super-app
      trigger: true
    - task: lint
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang}
        run:
          path: ./test_fmt.sh
          dir: super-app/scripts
        inputs:
          - name: super-app

    - task: unit
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang}
        run:
          path: sh
          args:
          - -exc
          - |
            ./scripts/go_deps.sh
            ./scripts/test_unit.sh
          dir: super-app/
        inputs:
          - name: super-app

    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang}
        run:
          path: sh
          args:
          - -exc
          - |
            ./scripts/go_deps.sh
            ./scripts/go_build.sh linux 0.0.1
          dir: super-app/
        inputs:
          - name: super-app
