---

platform: linux
image_resource:
  type: docker-image
  source: {repository: golang}
run:
  path: sh
  args:
  - -exc
  - |
    ./scripts/go_deps.sh
    ./scripts/go_build.sh linux $(cat ../semantic/version)
    mv super_*_linux_amd64 ../artifact_linux
  dir: super-app/
inputs:
  - name: super-app
  - name: semantic
outputs:
  - name: artifact_linux
